export const BLOG_POSTS = [
  {
    slug: 'bgmi-tournament-guide-2026',
    title: 'BGMI Tournament Guide 2026 - Complete Guide to Winning Real Money',
    excerpt: 'Master BGMI tournaments in 2026. Learn how to join tournaments, win real money, pro strategies, and step-by-step registration process.',
    image: '/blog/bgmi-tournament-guide-2026.jpg',
    category: 'Ultimate Guide',
    readTime: '15 min read',
    publishedAt: '2026-01-15',
    updatedAt: '2026-02-10',
    featured: true,
    changeFrequency: 'monthly',
    priority: 0.95,
    tags: ['bgmi tournament guide', 'bgmi real money', 'bgmi strategies'],
  },
  {
    slug: 'free-fire-tournament-tips',
    title: 'Free Fire Tournament Tips 2026 - Pro Strategies to Win Real Money',
    excerpt: 'Master Free Fire tournaments with expert tips. Learn character combos, weapon choices, and winning strategies for 1vs1 matches. Win cash prizes daily.',
    image: '/blog/free-fire-tips.jpg',
    category: 'Pro Guide',
    readTime: '12 min read',
    publishedAt: '2026-01-20',
    updatedAt: '2026-02-05',
    changeFrequency: 'monthly',
    priority: 0.9,
    tags: ['free fire tournament', 'free fire tips', 'free fire earning'],
  },
  {
    slug: 'how-to-earn-money-gaming-india',
    title: 'How to Earn Money Playing Games in India 2026 - Complete Guide',
    excerpt: 'Learn how to earn real money playing BGMI, Free Fire, and other games in India. Discover tournament platforms, earning methods, and income potential.',
    image: '/blog/earn-money-gaming.jpg',
    category: 'Earning Guide',
    readTime: '15 min read',
    publishedAt: '2026-01-22',
    updatedAt: '2026-02-15',
    changeFrequency: 'monthly',
    priority: 0.9,
    tags: ['earn money gaming', 'bgmi earnings', 'free fire earnings'],
  },
  {
    slug: 'bgmi-vs-free-fire-which-is-better',
    title: 'BGMI vs Free Fire 2026 - Which is Better for Tournaments & Earning?',
    excerpt: 'Complete comparison of BGMI vs Free Fire. Graphics, gameplay, earning potential, tournaments, and which game is better for you.',
    image: '/blog/bgmi-vs-free-fire.jpg',
    category: 'Comparison',
    readTime: '10 min read',
    publishedAt: '2026-01-25',
    updatedAt: '2026-02-12',
    changeFrequency: 'monthly',
    priority: 0.85,
    tags: ['bgmi vs free fire', 'best tournament game'],
  },
  {
    slug: 'pubg-mobile-tips-for-beginners',
    title: '10 Essential PUBG Mobile Tips for Beginners',
    excerpt: 'Master the basics of PUBG Mobile with these essential tips. Learn about landing spots, weapon selection, and survival strategies.',
    image: '/blog/pubg-tips.jpg',
    category: 'Tips & Tricks',
    readTime: '5 min read',
    publishedAt: '2025-12-28',
    updatedAt: '2026-01-05',
    changeFrequency: 'monthly',
    priority: 0.8,
    tags: ['pubg tips', 'pubg beginners'],
  },
  {
    slug: 'best-landing-spots-erangel',
    title: 'Best Landing Spots in Erangel 2025',
    excerpt: 'Discover the top landing spots in Erangel for high-tier loot and strategic advantage. Updated for the latest season.',
    image: '/blog/erangel-spots.jpg',
    category: 'Strategy',
    readTime: '7 min read',
    publishedAt: '2025-12-25',
    updatedAt: '2026-01-03',
    changeFrequency: 'monthly',
    priority: 0.78,
    tags: ['erangel landing spots', 'bgmi strategy'],
  },
  {
    slug: 'free-fire-character-guide',
    title: 'Free Fire Character Guide: Best Characters for Ranked',
    excerpt: 'Complete guide to Free Fire characters. Learn which characters are best for different playstyles and team compositions.',
    image: '/blog/ff-characters.jpg',
    category: 'Guides',
    readTime: '8 min read',
    publishedAt: '2025-12-22',
    updatedAt: '2026-01-02',
    changeFrequency: 'monthly',
    priority: 0.75,
    tags: ['free fire characters', 'ranked tips'],
  },
  {
    slug: 'how-to-improve-aim-mobile',
    title: 'How to Improve Your Aim in Mobile Gaming',
    excerpt: 'Professional tips to improve your aim and reflexes. Includes sensitivity settings, practice routines, and finger placement.',
    image: '/blog/aim-guide.jpg',
    category: 'Tips & Tricks',
    readTime: '6 min read',
    publishedAt: '2025-12-20',
    updatedAt: '2025-12-30',
    changeFrequency: 'monthly',
    priority: 0.72,
    tags: ['mobile aim', 'bgmi aim tips'],
  },
  {
    slug: 'esports-career-india',
    title: 'Building an Esports Career in India',
    excerpt: 'Everything you need to know about pursuing a professional esports career in India. From practice routines to team recruitment.',
    image: '/blog/esports-career.jpg',
    category: 'Esports',
    readTime: '10 min read',
    publishedAt: '2025-12-18',
    updatedAt: '2025-12-27',
    changeFrequency: 'monthly',
    priority: 0.7,
    tags: ['esports career', 'india esports'],
  },
  {
    slug: 'bgmi-update-latest-features',
    title: 'BGMI Latest Update: New Features & Changes',
    excerpt: 'Complete breakdown of the latest BGMI update including new maps, weapons, game modes, and balance changes.',
    image: '/blog/bgmi-update.jpg',
    category: 'News',
    readTime: '4 min read',
    publishedAt: '2025-12-15',
    updatedAt: '2025-12-26',
    changeFrequency: 'monthly',
    priority: 0.68,
    tags: ['bgmi update', 'bgmi news'],
  },
  {
    slug: 'how-to-win-bgmi-tournaments-2024',
    title: 'How to Win BGMI Tournaments in 2024 - Expert Guide',
    excerpt: 'Master competitive BGMI with these expert strategies and start winning real cash prizes.',
    image: '/blog/win-bgmi-tournaments.jpg',
    category: 'Pro Guide',
    readTime: '9 min read',
    publishedAt: '2024-01-15',
    updatedAt: '2025-12-20',
    changeFrequency: 'monthly',
    priority: 0.65,
    tags: ['win bgmi tournaments', 'bgmi pro tips'],
  },
];

export const FEATURED_BLOG_POST = BLOG_POSTS.find((post) => post.featured) || BLOG_POSTS[0];

export function getBlogPostBySlug(slug) {
  return BLOG_POSTS.find((post) => post.slug === slug);
}

export function getBlogSitemapEntries(baseUrl) {
  return BLOG_POSTS.map((post) => ({
    url: `${baseUrl}/blog/${post.slug}`,
    lastModified: new Date(post.updatedAt || post.publishedAt).toISOString(),
    changeFrequency: post.changeFrequency || 'monthly',
    priority: typeof post.priority === 'number' ? post.priority : 0.8,
  }));
}

export function getRssItems(baseUrl) {
  return BLOG_POSTS.map((post) => ({
    title: post.title,
    link: `${baseUrl}/blog/${post.slug}`,
    guid: `${baseUrl}/blog/${post.slug}`,
    description: post.excerpt,
    pubDate: new Date(post.publishedAt).toUTCString(),
    categories: [post.category, 'Esports'],
  }));
}
